name: Tests

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci

      - name: Run unit tests
        run: npm run test:unit

      - name: Run headless tests
        run: npm run test:headless

      - name: Make reports
        if: always()
        run: npm run test:report:ci

      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-html-report
          path: |
            reports/
          retention-days: 3

      - name: Upload test results to GitHub
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: vitest-junit
          path: reports/junit.xml

      - name: Test Report
        if: always()
        uses: dorny/test-reporter@v1
        with:
          name: Vitest Results
          path: reports/junit.xml
          reporter: java-junit
